# Generated by Django 5.0.1 on 2024-01-30 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediacredentials",
            name="bot_token",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
