# Generated by Django 5.0.1 on 2024-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0002_socialmediacredentials_bot_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediacredentials",
            name="youtube_client_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="youtube_client_secret",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="youtube_redirect_uri",
            field=models.URLField(default="https://your-default-redirect-uri.com"),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="youtube_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="youtube_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="api_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="api_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="bot_token",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="channel_username",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="facebook_client_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="socialmediacredentials",
            name="facebook_client_secret",
            field=models.CharField(max_length=255),
        ),
    ]
