# Generated by Django 5.0.1 on 2024-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0003_socialmediacredentials_youtube_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediacredentials",
            name="twitter_api_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="twitter_api_secret_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="twitter_bearer_token",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="socialmediacredentials",
            name="twitter_user_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
